### PR TITLE
Theme function to output image tag + other things

### PR DESCRIPTION
**Pull request by tlovett1**
This PR does the following:
- Adds the `cloudinary_image` function for outputting a Cloudinary image via PHP. It supports arguments similar to `cloudinary_url`.
- Adds the `format` transformation and defaults to `auto` for transformations done to `post_content.
- Adds `.editorconfig`
- Sets up Composer.
- Switches to 10up PHPCS rules.
- Updates documentation.

Let me know your thoughts.

### CODE REVIEW

**Comment by junaidbhura** [comment]
Hey @tlovett1 thanks for the PR!

I'm not sure I want to encourage people to use plugin-specific functions more than they need to. This plugin already hooks into `wp_get_attachment_image` which gets all the `srcset` and `lazy` functionality for free - and will also play nicely with other plugins and core - and will work for 99% of cases. This is also in keeping with the "just works" philosophy behind this plugin.

I think a function like `cloudinary_image` would be theme-territory with fall-backs as suggested here: https://github.com/junaidbhura/auto-cloudinary/wiki/Best-Practices

The only thing `wp_get_attachment_image` can't do with this plugin at the moment is to pass the transformation array, but they can be set on a global level or even using hooks: https://github.com/junaidbhura/auto-cloudinary/wiki/Filters

Let me know what you think!

**Comment by tlovett1** [comment]
I actually think a function to be used in the theme does make sense in the plugin. A function like the one I created needs to be used on all the sites I've ever set up Cloudinary. If it's not in this plugin, it would have to be copy pasted or added to an extension plugin.

**Comment by junaidbhura** [comment]
Hey @tlovett1 in your experience on the sites you've set up Cloudinary, is there something that this function does, that you couldn't do with `wp_get_attachment_image` ?

**Comment by tlovett1** [comment]
@junaidbhura Hmmm. My first thought is `wp_get_attachment_image` takes an image ID whereas I am usually referencing an image in the theme. Secondly, `wp_get_attachment_image` is based on image sizes registered in WP whereas when using Cloudinary, there is no reason to be limited by the image sizes registered in WP.

**Comment by junaidbhura** [comment]
Hey @tlovett1 my responses follow:

1. Hmm for images within the theme, I think a helper function in the theme to generate an image would be the best approach in case you decide to move away from Cloudinary and for local development (when the image is not yet available on Cloudinary), etc. Also themes can be very specific in what they need from a particular image. Ideally all images other than graphics are controlled from the back-end or the Customizer

2. `wp_get_attachment_image` allows you to pass an array as its size, which this plugin picks up, so you could just pass any dimensions in there

Let me know what you think!

**Pull request closed without merging**
